# Generated by Django 3.2.7 on 2023-04-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_generated', models.BooleanField(default=True)),
                ('quality_g', models.BooleanField(blank=True, default=False)),
                ('quality_a', models.BooleanField(blank=True, default=False)),
                ('quality_b', models.BooleanField(blank=True, default=False)),
                ('report_title', models.CharField(max_length=75)),
                ('owned', models.BooleanField(blank=True)),
                ('prop_address', models.CharField(blank=True, max_length=75)),
                ('prop_city', models.CharField(blank=True, max_length=50)),
                ('prop_state', models.CharField(blank=True, max_length=25)),
                ('prop_zip', models.CharField(blank=True, max_length=10, verbose_name='Zip')),
                ('bedrooms', models.CharField(blank=True, choices=[('', 'Select...'), ('0', '0'), ('1/2', '1/2'), ('1', '1'), ('1 1/2', '1 1/2'), ('2', '2'), ('2 1/2', '2 1/2'), ('3', '3'), ('3 1/2', '3 1/2'), ('4', '4'), ('4 1/2', '4 1/2'), ('5+', '5+')], default='', max_length=10)),
                ('bathrooms', models.CharField(blank=True, choices=[('', 'Select...'), ('0', '0'), ('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1 1/2', '1 1/2'), ('1 3/4', '1 3/4'), ('2', '2'), ('2 1/2', '2 1/2'), ('2 3/4', '2 3/4'), ('3', '3'), ('3 1/2', '3 1/2'), ('3 3/4', '3 3/4'), ('4', '4'), ('4 1/2', '4 1/2'), ('4 3/4', '4 3/4'), ('5+', '5+')], default='', max_length=10)),
                ('sqft', models.CharField(blank=True, max_length=30)),
                ('year_built', models.CharField(blank=True, max_length=4)),
                ('prop_description', models.TextField(blank=True)),
                ('prop_photo', models.ImageField(blank=True, upload_to='property_photos')),
                ('prop_mls', models.CharField(blank=True, max_length=30)),
                ('purchase_price', models.IntegerField()),
                ('purchase_closing_cost', models.IntegerField()),
                ('est_repair_cost', models.IntegerField(blank=True, null=True)),
                ('after_repair_value', models.IntegerField(blank=True, null=True)),
                ('annual_pv_growth', models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True)),
                ('cash_purchase', models.BooleanField(blank=True, default=False)),
                ('down_payment', models.CharField(blank=True, choices=[('', 'Select...'), ('0%', '0%'), ('3%', '3%'), ('3.5%', '3.5%'), ('5%', '5%'), ('7.5%', '7.5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%')], default='', max_length=10)),
                ('down_payment_2', models.IntegerField(blank=True, null=True)),
                ('loan_int_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('points', models.SmallIntegerField(blank=True, null=True)),
                ('loan_term', models.SmallIntegerField()),
                ('gross_monthly_rent', models.SmallIntegerField()),
                ('other_monthly_income', models.SmallIntegerField(blank=True, null=True)),
                ('annual_income_growth', models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True)),
                ('prop_annual_taxes', models.IntegerField()),
                ('monthly_insurance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('repairs_maint', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vacancy', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cap_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mgmt_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('electricity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gas', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('water_sewer', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hoa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('garbage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pmi', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('other_monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('annual_expenses_growth', models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True)),
                ('sales_expenses', models.DecimalField(blank=True, decimal_places=2, default=7.5, max_digits=4, null=True)),
                ('redfin_listing_url', models.URLField(blank=True)),
                ('zillow_zestimate_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
