# Generated by Django 3.2.7 on 2021-12-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrentalreport',
            name='quality_a',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='botrentalreport',
            name='quality_b',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='botrentalreport',
            name='quality_g',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
