# Generated by Django 3.2.7 on 2021-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPropCalcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=75)),
                ('prop_address', models.CharField(blank=True, max_length=75)),
                ('prop_city', models.CharField(blank=True, max_length=50)),
                ('prop_state', models.CharField(blank=True, max_length=25)),
                ('prop_zip', models.CharField(blank=True, max_length=10, verbose_name='Zip')),
                ('prop_annual_taxes', models.IntegerField(blank=True)),
                ('prop_mls', models.CharField(blank=True, max_length=30)),
                ('prop_photo', models.ImageField(blank=True, upload_to='')),
                ('prop_description', models.TextField(blank=True)),
                ('purchase_price', models.IntegerField()),
                ('after_repair_value', models.IntegerField()),
                ('purchase_closing_cost', models.IntegerField(blank=True)),
                ('est_repair_cost', models.IntegerField(blank=True)),
                ('cash_purchase', models.BooleanField(blank=True)),
                ('down_payment', models.CharField(blank=True, choices=[('', 'Select...'), ('0%', '0%'), ('3%', '3%'), ('3.5%', '3.5%'), ('5%', '5%'), ('7.5%', '7.5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%')], default='', max_length=10)),
                ('loan_int_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('points', models.SmallIntegerField(blank=True)),
                ('other_charges', models.IntegerField(blank=True)),
                ('fees_points_preference', models.BooleanField()),
                ('interest_only', models.BooleanField()),
                ('loan_term', models.SmallIntegerField()),
                ('cap_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('gross_monthly_rent', models.SmallIntegerField()),
                ('other_monthly_income', models.SmallIntegerField(blank=True)),
                ('electricity', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('water_sewer', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('pmi', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('garbage', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('hoa', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monthly_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('monthly_property_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('other_monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('vacancy', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('repairs_maint', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cap_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('mgmt_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('annual_income_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('annual_pv_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('annual_expenses_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('sales_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
    ]
