# Generated by Django 3.2.7 on 2021-11-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment', models.IntegerField(blank=True, max_length=3, null=True)),
                ('loan_int_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('loan_term', models.SmallIntegerField(blank=True, null=True)),
                ('repairs_maint', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vacancy', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cap_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mgmt_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('city_code', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
