# Generated by Django 3.2.7 on 2021-09-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210919_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpropcalcreport',
            name='fees_points_preference',
        ),
        migrations.RemoveField(
            model_name='rentalpropcalcreport',
            name='interest_only',
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('', 'Select...'), ('0', '0'), ('1/2', '1/2'), ('3/4', '3/4'), ('1', '1'), ('1 1/2', '1 1/2'), ('1 3/4', '1 3/4'), ('2', '2'), ('2 1/2', '2 1/2'), ('2 3/4', '2 3/4'), ('3', '3'), ('3 1/2', '3 1/2'), ('3 3/4', '3 3/4'), ('4', '4'), ('4 1/2', '4 1/2'), ('4 3/4', '4 3/4'), ('5+', '5+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('', 'Select...'), ('0', '0'), ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5+', '5+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='down_payment_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='sqft',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='monthly_insurance',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='monthly_property_taxes',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='purchase_closing_cost',
            field=models.IntegerField(default='0'),
        ),
    ]
