# Generated by Django 3.2.7 on 2021-11-09 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='max_beds',
            field=models.CharField(blank=True, choices=[('', 'No max'), ('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_price',
            field=models.CharField(blank=True, choices=[('', 'No max'), ('$50k', '$50k'), ('$75k', '$75k'), ('$100k', '$100k'), ('$125k', '$125k'), ('$150k', '$150k'), ('$175k', '$175k'), ('$200k', '$200k'), ('$225k', '$225k'), ('$250k', '$250k'), ('$275k', '$275k'), ('$300k', '$300k'), ('$325k', '$325k'), ('$350k', '$350k'), ('$375k', '$375k'), ('$400k', '$400k'), ('$425k', '$425k'), ('$450k', '$450k'), ('$475k', '$475k'), ('$500k', '$500k'), ('$550k', '$550k'), ('$600k', '$600k'), ('$650k', '$650k'), ('$700k', '$700k'), ('$750k', '$750k'), ('$800k', '$800k'), ('$850k', '$850k'), ('$900k', '$900k'), ('$950k', '$950k'), ('$1M', '$1M'), ('$1.25M', '$1.25M'), ('$1.50M', '$1.50M'), ('$1.75M', '$1.75M'), ('$2M', '$2M'), ('$2.25M', '$2.25M'), ('$2.50M', '$2.50M'), ('$2.75M', '$2.75M'), ('$3M', '$3M'), ('$3.25M', '$3.25M'), ('$3.50M', '$3.50M'), ('$3.75M', '$3.75M'), ('$4M', '$4M'), ('$4.25M', '$4.25M'), ('$4.50M', '$4.50M'), ('$4.75M', '$4.75M'), ('$5M', '$5M'), ('$6M', '$6M'), ('$7M', '$7M'), ('$8M', '$8M'), ('$9M', '$9M'), ('$10M', '$10M')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='min_baths',
            field=models.CharField(blank=True, choices=[('', 'No min'), ('1+', '1+'), ('1.5+', '1.5+'), ('2+', '2+'), ('2.5+', '2.5+'), ('3+', '3+'), ('4+', '4+'), ('5+', '5+'), ('6+', '6+')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='min_beds',
            field=models.CharField(blank=True, choices=[('', 'No min'), ('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='min_price',
            field=models.CharField(blank=True, choices=[('', 'No min'), ('$50k', '$50k'), ('$75k', '$75k'), ('$100k', '$100k'), ('$125k', '$125k'), ('$150k', '$150k'), ('$175k', '$175k'), ('$200k', '$200k'), ('$225k', '$225k'), ('$250k', '$250k'), ('$275k', '$275k'), ('$300k', '$300k'), ('$325k', '$325k'), ('$350k', '$350k'), ('$375k', '$375k'), ('$400k', '$400k'), ('$425k', '$425k'), ('$450k', '$450k'), ('$475k', '$475k'), ('$500k', '$500k'), ('$550k', '$550k'), ('$600k', '$600k'), ('$650k', '$650k'), ('$700k', '$700k'), ('$750k', '$750k'), ('$800k', '$800k'), ('$850k', '$850k'), ('$900k', '$900k'), ('$950k', '$950k'), ('$1M', '$1M'), ('$1.25M', '$1.25M'), ('$1.50M', '$1.50M'), ('$1.75M', '$1.75M'), ('$2M', '$2M'), ('$2.25M', '$2.25M'), ('$2.50M', '$2.50M'), ('$2.75M', '$2.75M'), ('$3M', '$3M'), ('$3.25M', '$3.25M'), ('$3.50M', '$3.50M'), ('$3.75M', '$3.75M'), ('$4M', '$4M'), ('$4.25M', '$4.25M'), ('$4.50M', '$4.50M'), ('$4.75M', '$4.75M'), ('$5M', '$5M'), ('$6M', '$6M'), ('$7M', '$7M'), ('$8M', '$8M'), ('$9M', '$9M'), ('$10M', '$10M')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='minor_civil_div',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='prop_type',
            field=models.CharField(choices=[('House', 'House'), ('Townhouse', 'Townhouse'), ('Condo', 'Condo'), ('Multi-family', 'Multi-family')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='down_payment',
            field=models.CharField(blank=True, choices=[('', 'Select...'), ('0%', '0%'), ('3%', '3%'), ('3.5%', '3.5%'), ('5%', '5%'), ('7.5%', '7.5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Choose State...'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
