# Generated by Django 3.2.7 on 2021-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210925_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='monthly_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='monthly_property_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
