# Generated by Django 3.2.7 on 2021-11-11 19:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20211109_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='bot_frequency',
            field=models.CharField(blank=True, choices=[('', 'Never'), ('Every hour', 'Every hour'), ('Every 6 hours', 'Every 6 hours'), ('2x/day', '2x/day'), ('1x/day', '1x/day'), ('Every other day', 'Every other day'), ('1x/week', '1x/week'), ('1x/month', '1x/month')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='minor_civil_div',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='prop_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Multifamily', 'Multifamily')], default=None, max_length=100),
        ),
    ]
