# Generated by Django 3.2.7 on 2021-09-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210925_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpropcalcreport',
            name='monthly_property_taxes',
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='est_repair_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='prop_annual_taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='purchase_closing_cost',
            field=models.IntegerField(default=0),
        ),
    ]
