# Generated by Django 3.2.7 on 2021-09-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20210925_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='prop_photo',
            field=models.ImageField(blank=True, upload_to='property_images'),
        ),
    ]
