# Generated by Django 3.2.7 on 2021-11-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20211113_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='addr_blacklist',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='blacklist_bool',
            field=models.BooleanField(default=True),
        ),
    ]
