# Generated by Django 3.2.7 on 2021-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20211124_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='cashflow_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='cashflow_top',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='coc_roi_bottom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='coc_roi_top',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='addr_blacklist',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='blacklist_bool',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='minor_civil_div',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
