# Generated by Django 3.2.7 on 2021-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_rentalpropcalcreport_prop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='prop_photo',
            field=models.ImageField(blank=True, upload_to='property_photos'),
        ),
    ]
