# Generated by Django 3.2.7 on 2021-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20211207_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='cashflow_bottom',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='cashflow_top',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
