# Generated by Django 3.2.7 on 2021-10-13 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_rentalpropcalcreport_prop_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
