# Generated by Django 3.2.7 on 2021-12-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20211207_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='quality_a',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='quality_b',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='quality_g',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
