# Generated by Django 3.2.7 on 2021-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20211013_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpropcalcreport',
            name='cap_rate',
        ),
        migrations.RemoveField(
            model_name='rentalpropcalcreport',
            name='other_charges',
        ),
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='year_built',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='after_repair_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('', 'Select...'), ('0', '0'), ('1/2', '1/2'), ('1', '1'), ('1 1/2', '1 1/2'), ('2', '2'), ('2 1/2', '2 1/2'), ('3', '3'), ('3 1/2', '3 1/2'), ('4', '4'), ('4 1/2', '4 1/2'), ('5+', '5+')], default='', max_length=10),
        ),
    ]
