# Generated by Django 3.2.7 on 2021-10-25 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0009_auto_20211013_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='annual_expenses_growth',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='annual_income_growth',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='annual_pv_growth',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='est_repair_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='prop_annual_taxes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='purchase_closing_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='sales_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=7.5, max_digits=4, null=True),
        ),
    ]
