# Generated by Django 3.2.7 on 2021-10-27 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0011_alter_rentalpropcalcreport_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropcalcreport',
            name='owned',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='rentalpropcalcreport',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
